-- upgrade n° de version
UPDATE `system` SET `value`='v1.3.0' WHERE `name`='medge';

-- ajustement form pour autosize
UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeAtcdPersoMedicaux,rows=6', 'medGeAtcdPersoMedicaux,rows=2') where internalName = 'medGeATCD';
UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeAtcdPersoChirugicaux,rows=6', 'medGeAtcdPersoChirugicaux,rows=2') where internalName = 'medGeATCD';
UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeAtcdFamiliaux,rows=6', 'medGeAtcdFamiliaux,rows=2') where internalName = 'medGeATCD';
UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'allergies,rows=2', 'allergies,rows=1') where internalName = 'medGeATCD';
UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, '- job', '- job,rows=1') where internalName = 'medGeATCD';
UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, '- toxiques', '- toxiques,rows=1') where internalName = 'medGeATCD';

UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeSynthesePatient,rows=8', 'medGeSynthesePatient,rows=2') where internalName = 'medGeSynthesePatient';

UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeSyntheseGrossesse,rows=5', 'medGeSyntheseGrossesse,rows=2') where internalName = 'medGeSyntheseObs';

UPDATE `forms` SET `javascript` = '$(document).ready(function() {\r\n\r\n  //calcul IMC\r\n  if ($(\'#id_imc_id\').length > 0) {\r\n\r\n    imc = imcCalc($(\'#id_poids_id\').val(), $(\'#id_taillePatient_id\').val());\r\n    if (imc > 0) {\r\n      $(\'#id_imc_id\').val(imc);\r\n    }\r\n\r\n    $(\"#patientLatCol\").on(\"keyup\", \"#id_poids_id , #id_taillePatient_id\", function() {\r\n      poids = $(\'#id_poids_id\').val();\r\n      taille = $(\'#id_taillePatient_id\').val();\r\n      imc = imcCalc(poids, taille);\r\n      $(\'#id_imc_id\').val(imc);\r\n      patientID = $(\'#identitePatient\').attr(\"data-patientID\");\r\n      setPeopleDataByTypeName(imc, patientID, \'imc\', \'#id_imc_id\', \'0\');\r\n\r\n    });\r\n  }\r\n\r\n  //ajutement auto des textarea en hauteur\r\n  autosize($(\'#formName_medGeATCD textarea\')); \r\n  \r\n});' where internalName = 'medGeATCD';
UPDATE `forms` SET `javascript` = '$(document).ready(function() {\r\n\r\n  //ajutement auto des textarea en hauteur\r\n  autosize($(\'#formName_medGeSyntheseObs textarea\')); \r\n  \r\n  // Si on change la DDR\r\n  $(\"#before_DDR\").on(\"dp.change\", function(e) {\r\n    calcAndDisplayTdj();\r\n    calcAndDisplayDdgt();\r\n    calcAndDisplayT9m();\r\n    if (typeof(dicomAutoSendPatient) != \"undefined\") {\r\n      if (dicomAutoSendPatient == true) {\r\n        prepareEcho(\'nopopup\');\r\n      }\r\n    }\r\n  });\r\n\r\n\r\n  // Si on change la DDG retenue\r\n  $(\"#before_ddgReel\").on(\"dp.change\", function(e) {\r\n    calcAndDisplayTdj();\r\n    calcAndDisplayT9m();\r\n    if (typeof(dicomAutoSendPatient) != \"undefined\") {\r\n      if (dicomAutoSendPatient == true) {\r\n        prepareEcho(\'nopopup\');\r\n      }\r\n    }\r\n  });\r\n\r\n  //close grossesseEnCours\r\n  $(\'body\').on(\"click\", \"#closeGro\", function(e) {\r\n    if (confirm(\"Voulez-vous fermer définitivement ce suivi de grossesse ?\")) {\r\n      if (confirm(\"Confirmez-vous réellement ?\")) {\r\n\r\n      } else {\r\n        e.preventDefault();\r\n      }\r\n    } else {\r\n      e.preventDefault();\r\n    }\r\n  });\r\n\r\n  calcAndDisplayDdgt();\r\n  calcAndDisplayTdj();\r\n  calcAndDisplayT9m()\r\n});\r\n\r\n// calculer et afficher terme du jour\r\nfunction calcAndDisplayTdj() {\r\n  tdj = tdjCalc($(\'#id_DDR_id\').val(), $(\'#id_ddgReel_id\').val());\r\n  if (tdj[\'status\'] == \'ok\') {\r\n    $(\'#id_termeDuJour_id\').val(tdj[\'human\']);\r\n    $(\'#id_termeDuJour_id\').attr(\'data-tdj4math\', tdj[\'math\']);\r\n  } else {\r\n    $(\'#id_termeDuJour_id\').val(\'\');\r\n    $(\'#id_termeDuJour_id\').attr(\'data-tdj4math\', \'\');\r\n  }\r\n}\r\n\r\n// calculer et afficher terme 9 mois\r\nfunction calcAndDisplayT9m() {\r\n  t9 = terme9mCalc($(\'#id_DDR_id\').val(), $(\'#id_ddgReel_id\').val());\r\n  if (t9[\'status\'] == \'ok\') {\r\n    $(\'#id_terme9mois_id\').val(t9[\'human\']);\r\n  } else {\r\n    $(\'#id_terme9mois_id\').val(\'\');\r\n  }\r\n}\r\n\r\n\r\n//calculer et afficher DDG théo\r\nfunction calcAndDisplayDdgt() {\r\n  ddgt = ddgtCalc($(\'#id_DDR_id\').val());\r\n  $(\'#id_ddg_id\').val(ddgt);\r\n}' where internalName = 'medGeSyntheseObs';
UPDATE `forms` SET `javascript` = '$(document).ready(function() {\r\n\r\n  //bouton de nouvelle grossesse\r\n  $(\"a.newGro\").on(\"click\", function(e) {\r\n    if (!confirm(\'Voulez-vous installer un nouveau suivi de grossesse ?\')) {\r\n      e.preventDefault();\r\n    }\r\n  });\r\n  \r\n  //ajutement auto des textarea en hauteur\r\n  autosize($(\'#formName_medGeSynthesePatient textarea\')); \r\n \r\n});' where internalName = 'medGeSynthesePatient';


UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeCsExamenDuJour,rows=10', 'medGeCsExamenDuJour,rows=3') where internalName = 'medGeConsultAdulte';
UPDATE `forms` SET `javascript` = '$(document).ready(function() {\r\n\r\n  //ajutement auto des textarea en hauteur\r\n  autosize($(\'#formName_medGeConsultAdulte textarea\')); \r\n\r\n});' where internalName = 'medGeConsultAdulte';

UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeCsDivVaccinationNotes,row=4', 'medGeCsDivVaccinationNotes,row=2') where internalName = 'medGeConsultVaccination';
UPDATE `forms` SET `javascript` = '$(document).ready(function() {\r\n\r\n  //ajutement auto des textarea en hauteur\r\n  autosize($(\'#formName_medGeConsultVaccination textarea\')); \r\n\r\n});' where internalName = 'medGeConsultVaccination';

UPDATE `forms` SET `yamlStructure` = replace(yamlStructure, 'medGeExamenObsDuJour,rows=10', 'medGeExamenObsDuJour,rows=3') where internalName = 'medGeConsultObs';
UPDATE `forms` SET `javascript` = '$(document).ready(function() {\r\n\r\n  //ajutement auto des textarea en hauteur\r\n  autosize($(\'#formName_medGeConsultObs textarea\')); \r\n\r\n});' where internalName = 'medGeConsultObs';
